const scenes=[
{id:'greet',tag:'GREETING',title:'初次见面',img:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=82',obj:'People · Eye contact · Greeting',cover:'基础社交',phrases:[['Nice to meet you.','很高兴认识你。','はじめまして。','Nice / MEET','初次见面直接使用'],['How’s it going?','最近怎么样？','調子どう？','HOW / GOING','朋友式寒暄'],['What should I call you?','我该怎么称呼你？','なんて呼べばいい？','CALL / YOU','确认称呼']]},
{id:'intro',tag:'INTRODUCTION',title:'自我介绍',img:'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=82',obj:'People · Conversation · Name',cover:'基础社交',phrases:[['I’m from China.','我来自中国。','中国から来ました。','FROM / CHINA','身份信息'],['I work in operations.','我做运营工作。','運営の仕事をしています。','WORK / OPERATIONS','职业介绍'],['I’m learning Japanese.','我正在学日语。','日本語を勉強しています。','LEARNING / JAPANESE','说明语言状态']]},
{id:'smalltalk',tag:'SMALL TALK',title:'日常寒暄',img:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=82',obj:'Friends · Weather · Casual talk',cover:'延续对话',phrases:[['It’s really hot today.','今天真的很热。','今日は本当に暑いですね。','HOT / TODAY','天气开场'],['Have you been here before?','你以前来过这里吗？','ここに来たことある？','BEEN / BEFORE','延续对话'],['What have you been up to lately?','你最近在忙什么？','最近何してる？','UP TO / LATELY','朋友聊天']]},
{id:'convenience',tag:'CONVENIENCE STORE',title:'便利店',img:'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=82',obj:'Cashier · Card terminal · Bag',cover:'生活交易',phrases:[['Can I pay by card?','可以刷卡吗？','カードで払えますか？','PAY / CARD','付款方式'],['Could I get a bag, please?','可以给我一个袋子吗？','袋をもらえますか？','GET / BAG','索要袋子'],['I don’t need a receipt.','我不需要小票。','レシートはいりません。','NEED / RECEIPT','结账收尾']]},
{id:'coffee',tag:'COFFEE SHOP',title:'咖啡店',img:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=82',obj:'Menu · Cup · Barista',cover:'餐饮',phrases:[['Could I get an iced coffee?','请给我一杯冰咖啡。','アイスコーヒーを一つお願いします。','ICED / COFFEE','点单'],['To go, please.','请打包带走。','持ち帰りでお願いします。','TO GO','堂食/外带'],['Can I get it without sugar?','可以不加糖吗？','砂糖なしにできますか？','WITHOUT / SUGAR','修改订单']]},
{id:'restaurant',tag:'RESTAURANT',title:'餐厅',img:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=82',obj:'Menu · Table · Server',cover:'餐饮',phrases:[['A table for two, please.','两位，谢谢。','二人です。','TABLE / TWO','入店'],['What do you recommend?','你推荐什么？','おすすめは何ですか？','RECOMMEND','点菜'],['Could we get the bill, please?','麻烦结账。','お会計お願いします。','GET / BILL','结账']]},
{id:'shopping',tag:'SHOPPING',title:'购物',img:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=82',obj:'Clothes · Price tag · Store',cover:'购物',phrases:[['How much is this?','这个多少钱？','これはいくらですか？','HOW MUCH','问价'],['Do you have this in a larger size?','有大一码的吗？','もう少し大きいサイズはありますか？','LARGER / SIZE','尺码'],['I’m just looking, thanks.','我只是看看，谢谢。','見ているだけです。','JUST / LOOKING','拒绝推销']]},
{id:'station',tag:'TRAIN STATION',title:'车站',img:'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=82',obj:'Platform · Sign · Ticket gate',cover:'交通',phrases:[['Which platform is it?','是哪个站台？','何番線ですか？','WHICH / PLATFORM','站台'],['Does this train go to Shinjuku?','这趟车到新宿吗？','この電車は新宿に行きますか？','TRAIN / GO','确认线路'],['Where can I buy a ticket?','在哪里买票？','切符はどこで買えますか？','BUY / TICKET','购票']]},
{id:'taxi',tag:'TAXI',title:'打车',img:'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1200&q=82',obj:'Car · Map · Destination',cover:'交通',phrases:[['Could you take me here?','可以带我去这里吗？','ここまでお願いします。','TAKE / HERE','给司机地址'],['How long will it take?','大概要多久？','どのくらいかかりますか？','HOW LONG','时间'],['Please stop here.','请在这里停。','ここで止めてください。','STOP / HERE','下车']]},
{id:'directions',tag:'DIRECTIONS',title:'问路',img:'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=1200&q=82',obj:'Map · Street · Landmark',cover:'交通',phrases:[['Excuse me, where is the station?','请问车站在哪里？','すみません、駅はどこですか？','WHERE / STATION','问地点'],['Is it far from here?','离这里远吗？','ここから遠いですか？','FAR / HERE','距离'],['Could you show me on the map?','可以在地图上指给我吗？','地図で教えてもらえますか？','SHOW / MAP','辅助理解']]},
{id:'hotel',tag:'HOTEL',title:'酒店',img:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=82',obj:'Reception · Key card · Room',cover:'住宿',phrases:[['I have a reservation.','我有预订。','予約しています。','HAVE / RESERVATION','入住'],['What time is check-out?','几点退房？','チェックアウトは何時ですか？','CHECK-OUT / TIME','规则'],['Could I leave my luggage here?','可以把行李寄存在这里吗？','荷物を預けてもいいですか？','LEAVE / LUGGAGE','寄存']]},
{id:'appointment',tag:'APPOINTMENT',title:'时间与约定',img:'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1200&q=82',obj:'Calendar · Phone · Time',cover:'时间协调',phrases:[['Are you free tonight?','你今晚有空吗？','今夜、暇？','FREE / TONIGHT','邀请'],['Can we meet at seven?','我们七点见可以吗？','7時に会える？','MEET / SEVEN','定时间'],['Can we move it to tomorrow?','可以改到明天吗？','明日に変更できる？','MOVE / TOMORROW','改期']]},
{id:'friends',tag:'FRIENDS',title:'朋友聊天',img:'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1200&q=82',obj:'Friends · Cafe · Talk',cover:'延续对话',phrases:[['What are you doing later?','你等会儿干嘛？','このあと何する？','DOING / LATER','延续'],['That sounds fun.','听起来不错。','楽しそう。','SOUNDS / FUN','回应'],['Let me know when you’re free.','你有空告诉我。','暇なとき教えて。','LET ME KNOW','继续联系']]},
{id:'invite',tag:'INVITE / DECLINE',title:'邀请与拒绝',img:'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=82',obj:'Friends · Plans · Phone',cover:'社交边界',phrases:[['Do you want to grab dinner?','要不要一起吃晚饭？','ご飯行かない？','GRAB / DINNER','邀请'],['I’d love to, but I can’t tonight.','很想去，但今晚不行。','行きたいけど、今日は無理。','LOVE / CAN’T','礼貌拒绝'],['Maybe another time.','下次吧。','また今度。','ANOTHER / TIME','留后路']]},
{id:'help',tag:'ASK FOR HELP',title:'请求帮助',img:'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=82',obj:'People · Help · Task',cover:'请求',phrases:[['Could you help me with this?','可以帮我一下吗？','これ、手伝ってもらえますか？','HELP / THIS','请求'],['Could you show me how?','可以教我怎么做吗？','やり方を教えてもらえますか？','SHOW / HOW','学习'],['Thanks, I really appreciate it.','谢谢，真的很感激。','本当に助かりました。','APPRECIATE','感谢']]},
{id:'repair',tag:'REPAIR THE CONVERSATION',title:'没听懂 / 修复对话',img:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=82',obj:'Conversation · Listening · Clarify',cover:'对话修复',phrases:[['Sorry, could you say that again?','不好意思，可以再说一遍吗？','すみません、もう一度お願いします。','SAY / AGAIN','请求重复'],['Could you speak a little slower?','可以说慢一点吗？','もう少しゆっくり話してもらえますか？','SPEAK / SLOWER','降低语速'],['What does that mean?','那是什么意思？','それはどういう意味ですか？','WHAT / MEAN','澄清含义']]},
{id:'phone',tag:'PHONE / MESSAGE',title:'电话与消息',img:'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=1200&q=82',obj:'Phone · Message · Call',cover:'通信',phrases:[['Can you hear me?','你听得到吗？','聞こえる？','HEAR / ME','通话'],['I’ll text you the address.','我把地址发给你。','住所をメッセージで送るね。','TEXT / ADDRESS','发信息'],['Sorry, I missed your call.','不好意思，我没接到你的电话。','電話に出られなくてごめん。','MISSED / CALL','回电']]},
{id:'health',tag:'HEALTH',title:'身体不舒服',img:'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=82',obj:'Pharmacy · Medicine · Pain',cover:'健康安全',phrases:[['I don’t feel well.','我不太舒服。','体調がよくないです。','FEEL / WELL','说明状态'],['I have a headache.','我头疼。','頭が痛いです。','HEADACHE','症状'],['Is there a pharmacy nearby?','附近有药店吗？','近くに薬局はありますか？','PHARMACY / NEARBY','找药店']]},
{id:'emergency',tag:'EMERGENCY',title:'突发情况',img:'https://images.unsplash.com/photo-1587745416684-47953f16f02f?auto=format&fit=crop&w=1200&q=82',obj:'Emergency · Phone · Help',cover:'健康安全',phrases:[['Please call an ambulance.','请叫救护车。','救急車を呼んでください。','CALL / AMBULANCE','紧急'],['I need help.','我需要帮助。','助けが必要です。','NEED / HELP','求助'],['I lost my wallet.','我钱包丢了。','財布をなくしました。','LOST / WALLET','丢失物品']]},
{id:'work',tag:'WORK',title:'工作简单交流',img:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=82',obj:'Office · Laptop · Meeting',cover:'工作',phrases:[['Can we go over this together?','我们可以一起过一下这个吗？','一緒に確認できますか？','GO OVER / TOGETHER','协作'],['I’ll send it by this afternoon.','我今天下午前发给你。','今日の午後までに送ります。','SEND / AFTERNOON','承诺'],['Could you clarify this part?','可以解释一下这部分吗？','この部分をもう少し説明してもらえますか？','CLARIFY / PART','澄清']]}
];
const all=[]; scenes.forEach(s=>s.phrases.forEach((p,i)=>all.push({id:`${s.id}-${i}`,sceneId:s.id,scene:s,p,en:p[0],cn:p[1],jp:p[2],stress:p[3],use:p[4]})));
let idx=0,lang='en',modalItem=null,qIndex=0; const KEY='talkloop-v3-state';
let state=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{marks:{},history:[],days:{}}}catch(e){return{marks:{},history:[],days:{}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dayKey(ts=Date.now()){return new Date(ts).toISOString().slice(0,10)}
function mark(item,type){state.marks[item.id]={type,time:Date.now(),next:nextReview(type,Date.now())};state.history.unshift({id:item.id,type,time:Date.now()});state.history=state.history.slice(0,300);state.days[dayKey()] = (state.days[dayKey()]||0)+1;save();app.dataset.mood=type;toast(type==='bad'?'已进入不熟强化库':type==='mid'?'已进入模糊强化库':'已归类为熟练');refresh();}
function nextReview(type,t){const h=type==='bad'?4:type==='mid'?18:72;return t+h*3600*1000}
function go(name){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(name).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));if(name==='library')renderLibrary();if(name==='review')renderReview();if(name==='dashboard'){drawCurve();renderCalendar();renderCoverage()}}
function setLang(v){lang=v;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.lang===v));renderLesson()}
function renderLesson(){const x=all[idx];sceneBg.style.backgroundImage=`url('${x.scene.img}')`;sceneTag.textContent=x.scene.tag;sceneObj.innerHTML=`${x.scene.obj}<small>${x.scene.title} · ${x.use}</small>`;intent.textContent=x.scene.cover+' · '+x.use;enBlock.style.display=lang==='en'?'block':'none';jpBlock.style.display=lang==='jp'?'block':'none';enPhrase.textContent=x.en;enPron.textContent=`重音 / 关键词：${x.stress}`;jpPhrase.textContent=x.jp;jpPron.textContent='自然口语场景表达 · 点击发音听系统语音';meaning.textContent=x.cn;meaning.classList.remove('show');learnI.textContent=idx+1;learnN.textContent=all.length;learnBar.style.width=((idx+1)/all.length*100)+'%';tip.textContent=`场景：${x.scene.title}。先看真人/实物画面理解意图，再听声音，再主动说。`;}
function next(){idx=(idx+1)%all.length;renderLesson()}
function grade(type){mark(all[idx],type);next()}
function toggleMeaning(){meaning.classList.toggle('show')}
function speakCurrent(rate=1,item=all[idx]){if(!('speechSynthesis'in window)){toast('当前浏览器不支持系统发音');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(lang==='en'?item.en:item.jp);u.lang=lang==='en'?'en-US':'ja-JP';u.rate=rate;speechSynthesis.speak(u)}
function toast(t){toastBox.textContent=t;toastBox.classList.add('show');setTimeout(()=>toastBox.classList.remove('show'),1400)}
let sx=0,sy=0;swipe.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});swipe.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy))grade(dx>0?'good':'bad')});
function groups(type){return all.filter(x=>state.marks[x.id]?.type===type)}
function renderLibrary(){const arr=[...groups('mid'),...groups('bad')];libraryGrid.innerHTML=arr.length?arr.map(x=>`<button class="fuzzy" onclick="openItem('${x.id}')"><span class="countBadge">${state.marks[x.id].type==='bad'?'不熟':'模糊'}</span><div class="thumb" style="background-image:url('${x.scene.img}')"></div><div class="info"><b>${x.en}</b><span>${x.jp}</span></div></button>`).join(''):'<div class="card empty" style="grid-column:1/-1">还没有模糊/不熟记录。学习页点击“模糊”或“不熟”后会自动进入这里。</div>'}
function openItem(id){modalItem=all.find(x=>x.id===id);if(!modalItem)return;modalBg.style.backgroundImage=`url('${modalItem.scene.img}')`;modalEn.textContent=modalItem.en;modalJp.textContent=modalItem.jp;modalCn.textContent=modalItem.cn;modalMeta.textContent=`${modalItem.scene.title} · ${modalItem.use} · ${modalItem.stress}`;modal.classList.add('open');setTimeout(()=>speakItem(1),300)}
function closeModal(){modal.classList.remove('open')}
function speakItem(rate=1){if(!modalItem)return; const u=new SpeechSynthesisUtterance(lang==='en'?modalItem.en:modalItem.jp);u.lang=lang==='en'?'en-US':'ja-JP';u.rate=rate;speechSynthesis.cancel();speechSynthesis.speak(u)}
function modalGrade(type){if(!modalItem)return;mark(modalItem,type);closeModal();renderLibrary()}
function drawCurve(){const c=curve,ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=170*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=c.clientWidth,H=170;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#20252d';ctx.lineWidth=1;for(let i=1;i<5;i++){let y=20+i*28;ctx.beginPath();ctx.moveTo(28,y);ctx.lineTo(W-8,y);ctx.stroke()}const lines=[['#ff6f8e',.55],['#ffb94d',1.3],['#4bd6af',3.4]];lines.forEach(([col,s])=>{ctx.strokeStyle=col;ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<=W-42;x++){let t=x/(W-42)*7;let r=Math.exp(-t/s);let px=28+x,py=145-r*118;if(x===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)}ctx.stroke()});ctx.fillStyle='#727b88';ctx.font='10px -apple-system';['0','1d','3d','7d'].forEach((v,i)=>ctx.fillText(v,25+(W-60)*(i/3),163))}
function renderCalendar(){calendar.innerHTML='';const today=new Date();for(let i=27;i>=0;i--){const d=new Date(today);d.setDate(today.getDate()-i);const key=d.toISOString().slice(0,10),n=state.days[key]||0;const el=document.createElement('div');el.className='day'+(i===0?' today':'');el.dataset.l=n>8?3:n>3?2:n?1:0;el.textContent=d.getDate();calendar.appendChild(el)}}
function renderCoverage(){const marked=Object.keys(state.marks).length;const sceneTouched=new Set(Object.keys(state.marks).map(id=>all.find(x=>x.id===id)?.sceneId).filter(Boolean)).size;const repairTotal=all.filter(x=>x.scene.cover==='对话修复').length;const repairDone=all.filter(x=>x.scene.cover==='对话修复'&&state.marks[x.id]).length;coverage.innerHTML=row('核心场景覆盖',sceneTouched,scenes.length)+row('核心表达采样',marked,all.length)+row('对话修复表达',repairDone,repairTotal)+row('生活/交易/交通场景',countCat(['生活交易','餐饮','购物','交通','住宿']),all.filter(x=>['生活交易','餐饮','购物','交通','住宿'].includes(x.scene.cover)).length)}
function countCat(cats){return all.filter(x=>cats.includes(x.scene.cover)&&state.marks[x.id]).length}
function row(name,a,b){const p=Math.round((a/Math.max(1,b))*100);return `<div class="coverage-row"><div><span>${name}</span><div class="bar"><i style="width:${p}%"></i></div></div><em>${a}/${b} · ${p}%</em></div>`}
function renderReview(){const bad=groups('bad'),mid=groups('mid'),good=groups('good');badChips.innerHTML=chips(bad,'bad');midChips.innerHTML=chips(mid,'mid');goodChips.innerHTML=chips(good,'good');const due=all.filter(x=>state.marks[x.id]&&state.marks[x.id].next<=Date.now());dueCount.textContent=due.length;badCount.textContent=bad.length;midCount.textContent=mid.length;goodCount.textContent=good.length;setQuestion()}
function chips(arr,t){return arr.length?arr.slice(0,16).map(x=>`<span class="chip ${t}" onclick="openItem('${x.id}')">${x.en}</span>`).join(''):'<span class="chip">暂无</span>'}
const questions=[['你在便利店结账，想问能不能刷卡。不要翻译中文，直接说英语。','Can I pay by card?'],['对方没听清你的日语，你想请他再说一遍。','すみません、もう一度お願いします。'],['你在咖啡店，想点一杯冰咖啡并带走。先用英语完成。','Could I get an iced coffee? / To go, please.'],['你和朋友聊天，对方说今晚有空。你自然邀请对方一起吃饭。','Do you want to grab dinner?']];
function setQuestion(){qText.textContent=questions[qIndex][0];answer.value='';feedback.classList.remove('show')}
function submitAnswer(){if(!answer.value.trim()){toast('先给出你的回答');return}feedback.innerHTML=`<b>检查重点：</b>是否完成现实意图，而不是逐字翻译。一个可行表达：${questions[qIndex][1]}<br><br>下一问会改变场景或语言条件。`;feedback.classList.add('show');setTimeout(()=>{qIndex=(qIndex+1)%questions.length;setQuestion()},3300)}
function refresh(){homeBad.textContent=groups('bad').length;homeMid.textContent=groups('mid').length;homeGood.textContent=groups('good').length;const done=Object.keys(state.marks).length;homeDone.textContent=done;const total=Math.max(1,done),g=groups('good').length,m=groups('mid').length;levelText.textContent=g/total>.72?'L4 · 无提示能说':g/total>.42?'L3 · 提示后能说':'L2 · 听得懂';renderCoverage();renderLibrary();renderReview()}
function startMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Safari 网页语音识别支持有限，可用系统听写');return}const r=new SR();r.lang=lang==='en'?'en-US':'ja-JP';r.onresult=e=>toast('识别：'+e.results[0][0].transcript);r.onerror=()=>toast('语音识别未成功');r.start()}
window.addEventListener('resize',drawCurve);renderLesson();refresh();setTimeout(()=>{drawCurve();renderCalendar()},100);
