const KEY='talkloop7';
let st=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||{m:{},h:[],d:{},mood:'good',lang:'en'}}catch(e){return{m:{},h:[],d:{},mood:'good',lang:'en'}}})();
let ix=0,lang=st.lang||'en',filter='all',dScene='greeting',dTurn=0,dLang=lang,qx=0;
const $=x=>document.getElementById(x),app=$('app');app.dataset.mood=st.mood||'good';
const HEALTH_VIDEO='https://videos.pexels.com/video-files/30141938/12927309_1080_1920_30fps.mp4';
const JP_ONLY=['https://videos.pexels.com/video-files/12893501/12893501-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/9046233/9046233-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/6602066/6602066-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/8554081/8554081-hd_1080_1920_25fps.mp4'];
function save(){try{localStorage.setItem(KEY,JSON.stringify(st))}catch(e){}}
function key(ts=Date.now()){let d=new Date(ts);return d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate()}
function marked(t){return items.filter(x=>st.m[x.id]&&(t==='all'||st.m[x.id]===t))}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(window._toastT);window._toastT=setTimeout(()=>$('toast').classList.remove('show'),1300)}
function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));$(p).classList.add('on');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.p===p));if(p==='library')renderLib();if(p==='dialog')renderD();if(p==='check'){draw();cal();renderQ()}document.querySelector('.content').scrollTop=0}
function openLib(f){filter=f;go('library')}
function refresh(){let a=marked('all').length,b=marked('bad').length,m=marked('mid').length,g=marked('good').length;$('nAll').textContent=a;$('nBad').textContent=b;$('nMid').textContent=m;$('nGood').textContent=g;$('level').textContent=g/Math.max(1,a)>.6?'L4 · 无提示能说':g/Math.max(1,a)>.3?'L3 · 提示后能说':'L2 · 听得懂';let sc=new Set(marked('all').map(x=>x.si)).size;$('coverage').innerHTML=row('核心场景覆盖',sc,20)+row('核心表达采样',a,60)+row('多轮对话回合',120,120)+row('对话修复表达',marked('all').filter(x=>x.s[0]==='repair').length,3)}
function row(n,a,b){let p=Math.round(a/Math.max(1,b)*100);return `<div class=row><div>${n}<div class=bar><i style="width:${p}%"></i></div></div><span class=tiny>${a}/${b} · ${p}%</span></div>`}
function enSources(item){const id=item.s[0];if(['greeting','intro','smalltalk','appointment','friends','invite','thanks'].includes(id))return [EN[0]];if(['convenience','cafe','restaurant','shopping'].includes(id))return [EN[1]];if(['transport','directions'].includes(id))return [EN[2]];if(id==='hotel')return [EN[3]];if(id==='health')return [HEALTH_VIDEO];return [EN[4]]}
function clip(item,l=lang,turn=0){let n=item.si*3+item.pi+turn;if(l==='jp'){return{srcs:[JP_ONLY[n%JP_ONLY.length]],start:(item.pi*2.1+turn*1.25)%8,len:5+((item.pi+turn)%3)}}return{srcs:enSources(item),start:(item.pi*2.2+turn*1.2)%8,len:5+((item.pi+turn)%3)}}
function playClip(item,v,ph,l=lang,turn=0){let c=clip(item,l,turn),j=0,len=Math.min(8,Math.max(3,c.len));ph.style.display='block';ph.style.backgroundImage=`url('${IM[item.si%IM.length]}')`;v.style.display='none';v.onerror=null;v.onloadedmetadata=null;if(v._tm)v.removeEventListener('timeupdate',v._tm);function load(){if(!c.srcs[j]){v.style.display='none';ph.style.display='block';return}v.src=c.srcs[j];v.muted=true;v.playsInline=true;v.preload='metadata';v.onloadedmetadata=()=>{let stt=Math.min(c.start,Math.max(0,(v.duration||len)-len-.1));v._s=stt;v._l=len;try{v.currentTime=stt}catch(e){}v.style.display='block';ph.style.display='none';v.play().catch(()=>{j++;load()})};v.onerror=()=>{j++;load()};v.load()}v._tm=()=>{if(v.currentTime>=(v._s||0)+(v._l||len)){try{v.currentTime=v._s||0}catch(e){}v.play().catch(()=>{})}};v.addEventListener('timeupdate',v._tm);load()}
function render(){let x=items[ix],s=x.s;$('tag').textContent=s[2];$('meta').innerHTML=s[3]+`<small>${s[1]} · 第 ${x.pi+1}/3 条</small>`;playClip(x,$('vid'),$('photo'));$('intent').textContent=s[1];$('enP').textContent=x.en;$('enR').textContent='听自然重音 → 跟读 → 无提示主动说';$('jpP').textContent=x.jp;$('meaning').textContent=x.cn;$('meaning').classList.remove('show');$('tip').textContent=lang==='jp'?'日本語模式只调用女性交流素材池；优先日常咖啡店、柜台、办公室等交流语境。若视频源加载失败则停留在静态场景，不回退到混合人物视频。':'视频按场景类型匹配，并为每条表达切不同 3–8 秒动作片段。评分会持续改变整页光波氛围。';$('counter').textContent=(ix+1)+'/60';$('prog').style.width=(ix+1)/60*100+'%';$('en').style.display=lang==='en'?'block':'none';$('jp').style.display=lang==='jp'?'block':'none';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.l===lang))}
function langSet(l){lang=l;st.lang=l;save();render()}
function grade(t){let x=items[ix];st.m[x.id]=t;st.h.unshift([x.id,t,Date.now()]);st.h=st.h.slice(0,500);st.d[key()]=(st.d[key()]||0)+1;st.mood=t;save();app.dataset.mood=t;toast(t==='mid'?'模糊：黄橙光波保持脉冲':t==='bad'?'不熟：红紫光波持续强化':'熟练：蓝绿光波缓慢流动');refresh();ix=(ix+1)%60;setTimeout(render,100)}
function speak(rate=1){let x=items[ix];if(!('speechSynthesis'in window))return toast('当前浏览器不支持系统发音');speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(lang==='en'?x.en:x.jp);u.lang=lang==='en'?'en-US':'ja-JP';u.rate=rate;speechSynthesis.speak(u)}
function filters(){return ['all','bad','mid','good'].map(x=>`<button class="f ${filter===x?'on':''}" onclick="filter='${x}';renderLib()">${x==='all'?'全部':x==='bad'?'不熟':x==='mid'?'模糊':'熟练'}</button>`).join('')}
function renderLib(){$('filters').innerHTML=filters();let a=marked(filter);$('lib').innerHTML=a.length?a.map(x=>`<button class=rec onclick="ix=${items.indexOf(x)};go('learn');render()"><div class=th style="background-image:url('${IM[x.si%IM.length]}')"></div><div class=in><b>${x.en}</b><span>${x.jp}</span></div></button>`).join(''):'<div class="card tiny" style="padding:24px;grid-column:1/-1">暂无记录。训练页评分后会自动进入这里。</div>'}
function turns(s){return (D[s[0]]||[]).map(x=>({r:x[0],en:x[1],jp:x[2]}))}
function renderD(){if(!$('dsel').options.length)$('dsel').innerHTML=S.map(s=>`<option value="${s[0]}">${s[1]}</option>`).join('');$('dsel').value=dScene;let si=S.findIndex(s=>s[0]===dScene),s=S[si],ts=turns(s),t=ts[dTurn]||ts[0],sceneItems=items.filter(x=>x.si===si),base=sceneItems[Math.floor(dTurn/2)%sceneItems.length];$('dtag').textContent=s[2];$('dmeta').innerHTML=s[3]+`<small>${s[1]} · 第 ${dTurn+1}/6 轮</small>`;playClip(base,$('dvid'),$('dphoto'),dLang,dTurn);$('drole').textContent=t.r==='partner'?'Partner · 对方':'You · 你';$('dbub').className='bubble '+(t.r==='you'?'you':'');$('dtext').textContent=dLang==='en'?t.en:t.jp;$('dcount').textContent=(dTurn+1)+'/6';$('dlang').textContent=dLang==='en'?'日本語':'English'}
function speakD(){let s=S.find(x=>x[0]===dScene),t=turns(s)[dTurn];if(!t)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(dLang==='en'?t.en:t.jp);u.lang=dLang==='en'?'en-US':'ja-JP';speechSynthesis.speak(u)}
function nextD(){dTurn=(dTurn+1)%6;renderD()}
const Q=[['你在便利店结账，直接用英语问能不能刷卡。','Can I pay by card?'],['对方说太快，用日语请对方再说一遍。','すみません、もう一度お願いします。'],['咖啡店点冰咖啡并说明带走。','Could I get an iced coffee? To go, please.'],['朋友邀请你今晚吃饭，但你想改到明天。','Can we move it to tomorrow? / 明日に変えられますか？']];
function draw(){let c=$('curve'),ctx=c.getContext('2d'),w=c.clientWidth,h=150;c.width=w*devicePixelRatio;c.height=h*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);ctx.clearRect(0,0,w,h);[['#ff6f95',.6],['#ffbe59',1.4],['#55ddbe',3.2]].forEach(([co,k])=>{ctx.strokeStyle=co;ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<w-24;x++){let t=x/(w-24)*7,y=130-Math.exp(-t/k)*105;x?ctx.lineTo(12+x,y):ctx.moveTo(12,y)}ctx.stroke()})}
function cal(){$('cal').innerHTML='';let d=new Date();for(let i=27;i>=0;i--){let x=new Date(d);x.setDate(d.getDate()-i);let k=key(x.getTime()),n=st.d[k]||0;$('cal').innerHTML+=`<div class="day ${n>7?'c':n>3?'b':n?'a':''}">${x.getDate()}</div>`}}
function renderQ(){$('q').textContent=Q[qx][0];$('ans').value='';$('fb').classList.remove('show')}
function submit(){if(!$('ans').value.trim())return toast('先回答');$('fb').innerHTML='参考表达：'+Q[qx][1]+'<br>重点是完成现实意图，不是逐字翻译。';$('fb').classList.add('show');setTimeout(()=>{qx=(qx+1)%Q.length;renderQ()},2800)}
let sx=0,sy=0;document.querySelector('#learn .card').addEventListener('touchstart',e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});document.querySelector('#learn .card').addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy))grade(dx>0?'good':'bad')},{passive:true});
window.addEventListener('resize',()=>{if($('check').classList.contains('on'))draw()});refresh();render();renderLib();renderD();draw();cal();renderQ();console.log('TalkLoop v7 checks:',{scenes:S.length,coreExpressions:items.length,dialogueTurns:Object.values(D).reduce((n,x)=>n+x.length,0),mood:app.dataset.mood});