const KEY='talkloop8';
let st=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||{m:{},h:[],d:{},mood:'good',lang:'en',vis:{},streak:{}}}catch(e){return{m:{},h:[],d:{},mood:'good',lang:'en',vis:{},streak:{}}}})();
let ix=0,lang=st.lang||'en',filter='all',dScene='greeting',dTurn=0,dLang=lang,qx=0;
const $=x=>document.getElementById(x),app=$('app');app.dataset.mood=st.mood||'good';
function save(){try{localStorage.setItem(KEY,JSON.stringify(st))}catch(e){}}
function dayKey(ts=Date.now()){const d=new Date(ts);return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function marked(t='all'){return ITEMS.filter(x=>st.m[x.id]&&(t==='all'||st.m[x.id].type===t))}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(window._tt);window._tt=setTimeout(()=>$('toast').classList.remove('show'),1300)}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));$(p).classList.add('on');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.p===p));if(p==='library')renderLib();if(p==='dialog')renderD();if(p==='check'){draw();cal();renderAudit();renderQ()}document.querySelector('.content').scrollTop=0}
function openLib(f){filter=f;go('library')}
function row(n,a,b){const p=Math.round(a/Math.max(1,b)*100);return `<div class=row><div>${n}<div class=bar><i style="width:${p}%"></i></div></div><span class=tiny>${a}/${b} · ${p}%</span></div>`}
function refresh(){const a=marked().length,b=marked('bad').length,m=marked('mid').length,g=marked('good').length;$('nAll').textContent=a;$('nBad').textContent=b;$('nMid').textContent=m;$('nGood').textContent=g;const gr=g/Math.max(1,a);$('level').textContent=gr>.68?'L4 · 无提示能说':gr>.32?'L3 · 提示后能说':'L2 · 听得懂';const sc=new Set(marked().map(x=>x.scene.id)).size;const due=ITEMS.filter(x=>st.m[x.id]&&st.m[x.id].next<=Date.now()).length;$('coverage').innerHTML=row('核心场景覆盖',sc,20)+row('高频表达采样',a,400)+row('多轮对话回合',200,200)+row('对话修复表达',marked().filter(x=>x.scene.id==='repair').length,20);$('dueHome').textContent=due;$('weakHome').textContent=b+m;$('recentHome').textContent=st.h.length?ITEMS.find(x=>x.id===st.h[0].id)?.en||'继续训练':'尚未开始'}
function interval(type,streak){if(type==='bad')return 3*3600e3;if(type==='mid')return (12+Math.min(streak,4)*6)*3600e3;return (48+Math.min(streak,8)*24)*3600e3}
function grade(type){const x=ITEMS[ix],streak=type==='good'?(st.streak[x.id]||0)+1:0;st.streak[x.id]=streak;st.m[x.id]={type,time:Date.now(),next:Date.now()+interval(type,streak)};st.h.unshift({id:x.id,type,time:Date.now()});st.h=st.h.slice(0,800);st.d[dayKey()]=(st.d[dayKey()]||0)+1;st.mood=type;app.dataset.mood=type;save();toast(type==='bad'?'已进入不熟强化':type==='mid'?'已进入模糊强化':'已进入熟练长间隔');refresh();setTimeout(()=>{ix=pickNextIndex();render()},120)}
function pickNextIndex(){const now=Date.now();let ranked=ITEMS.map((x,i)=>{const m=st.m[x.id];let score=0;if(!m)score+=24;else if(m.next<=now)score+=m.type==='bad'?100:m.type==='mid'?70:35;else score+=m.type==='bad'?42:m.type==='mid'?24:4;score+=Math.random()*8;return{i,score}}).sort((a,b)=>b.score-a.score);return ranked[0].i}
function startAdaptive(){ix=pickNextIndex();render();go('learn')}
const mediaState=new WeakMap();
function pools(item,l){return (l==='jp'?VIDEO_JP:VIDEO_EN)[item.scene.id]||[]}
function stopMedia(v){const s=mediaState.get(v);if(s&&s.timer)clearTimeout(s.timer);v.onloadedmetadata=v.onerror=v.oncanplay=null;try{v.pause()}catch(e){}}
function remix(item,v,ph,l=lang,reason='auto'){stopMedia(v);const pool=pools(item,l);const k=item.id+'|'+l;st.vis[k]=(st.vis[k]||0)+1;save();const visit=st.vis[k],seed=hash(k+'|'+visit+'|'+Math.floor(Date.now()/9000));let pos=pool.length?seed%pool.length:0,tries=0;const len=3+(seed%6),start=(seed%11)+((item.pi%4)*1.15),scene=v.closest('.scene');scene.dataset.remix='1';ph.style.backgroundImage=`url('${item.scene.img}')`;ph.style.display='block';v.style.display='none';function tryOne(){if(!pool.length||tries>=pool.length){v.style.display='none';ph.style.display='block';return}const src=pool[(pos+tries)%pool.length];tries++;v.src=src;v.muted=true;v.playsInline=true;v.preload='metadata';v.onerror=tryOne;v.onloadedmetadata=()=>{const dur=isFinite(v.duration)?v.duration:0,s=Math.max(0,Math.min(start,Math.max(0,dur-len-.15)));v._clipStart=s;v._clipLen=Math.min(8,Math.max(3,Math.min(len,dur||len)));try{v.currentTime=s}catch(e){}v.style.display='block';ph.style.display='none';v.play().catch(tryOne)};v.ontimeupdate=()=>{if(v.currentTime>=(v._clipStart||0)+(v._clipLen||len)-.08)remix(item,v,ph,l,'segment')};v.load()}tryOne()}
function render(){const x=ITEMS[ix],s=x.scene;$('tag').textContent=s.tag;$('meta').innerHTML=`${s.meta}<small>${s.zh} · ${x.func} · 动作：${x.action}</small>`;$('live').innerHTML='<i></i>实时场景混剪';remix(x,$('vid'),$('photo'),lang,'render');$('intent').textContent=`${s.zh} · ${x.func}`;$('enP').textContent=x.en;$('enR').textContent='自然语速 → 慢速 → 无提示主动说';$('jpP').textContent=x.jp;$('jpR').textContent='女性交流视频素材池 · 日语语境 · 每段自动换片';$('meaning').textContent=x.cn;$('meaning').classList.remove('show');$('tip').textContent=lang==='jp'?'日本語模式会调用女性交流视频池，并在每个 3–8 秒片段结束后重新选择素材/时间片；它是“实时场景编排”，不是云端 AI 即时生成真人视频。':'每条表达都带动作标签，视频会按场景池 + 表达 + 当前训练次数实时重新编排，避免一直循环同一段。';$('counter').textContent=(ix+1)+'/400';$('prog').style.width=(ix+1)/400*100+'%';$('en').style.display=lang==='en'?'block':'none';$('jp').style.display=lang==='jp'?'block':'none';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.l===lang))}
function langSet(l){lang=l;st.lang=l;save();render()}
function manualRemix(){remix(ITEMS[ix],$('vid'),$('photo'),lang,'manual');toast('已生成新的场景混剪')}
function speak(rate=1){const x=ITEMS[ix];if(!('speechSynthesis'in window))return toast('浏览器不支持系统发音');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(lang==='en'?x.en:x.jp);u.lang=lang==='en'?'en-US':'ja-JP';u.rate=rate;speechSynthesis.speak(u)}
let sx=0,sy=0;$('learnCard').addEventListener('touchstart',e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});$('learnCard').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy))grade(dx>0?'good':'bad')},{passive:true});
function renderFilters(){const fs=[['all','全部'],['bad','不熟'],['mid','模糊'],['good','熟练']];$('filters').innerHTML=fs.map(([k,n])=>`<button class="f ${filter===k?'on':''}" onclick="filter='${k}';renderLib()">${n}</button>`).join('')}
function renderLib(){renderFilters();const arr=marked(filter).sort((a,b)=>(st.m[b.id]?.time||0)-(st.m[a.id]?.time||0));$('lib').innerHTML=arr.length?arr.map(x=>`<button class=rec onclick="ix=${ITEMS.indexOf(x)};render();go('learn')"><div class=th style="background-image:url('${x.scene.img}')"></div><div class=in><b>${x.en}</b><span>${x.jp} · ${st.m[x.id].type}</span></div></button>`).join(''):`<div class="card" style="padding:24px;grid-column:1/-1;color:#8f99ad">当前分类暂无记录。训练页评分后会自动进入这里。</div>`}
function fillDialogSelect(){if($('dsel').options.length)return;$('dsel').innerHTML=SCENES.map(s=>`<option value="${s.id}">${s.zh} · 10轮</option>`).join('')}
function renderD(){fillDialogSelect();const sc=SCENES.find(s=>s.id===dScene)||SCENES[0],turns=DIALOGUES[sc.id],t=turns[dTurn],fake={id:sc.id+'-d'+dTurn,scene:sc,pi:dTurn,action:t.action};$('dtag').textContent=sc.tag;$('dmeta').innerHTML=`${sc.meta}<small>${sc.zh} · 第 ${dTurn+1}/10 轮 · ${t.func}</small>`;remix(fake,$('dvid'),$('dphoto'),dLang,'dialog');$('dbub').classList.toggle('you',t.role==='u');$('drole').textContent=t.role==='u'?'You · 你':'Partner · 对方';$('dtext').textContent=dLang==='en'?t.en:t.jp;$('dcount').textContent=(dTurn+1)+'/10';$('dlang').textContent=dLang==='en'?'日本語':'English'}
function nextD(){dTurn=(dTurn+1)%10;renderD()}
function remixD(){const sc=SCENES.find(s=>s.id===dScene),t=DIALOGUES[sc.id][dTurn],fake={id:sc.id+'-d'+dTurn,scene:sc,pi:dTurn,action:t.action};remix(fake,$('dvid'),$('dphoto'),dLang,'manual')}
function speakD(){const t=DIALOGUES[dScene][dTurn];if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(dLang==='en'?t.en:t.jp);u.lang=dLang==='en'?'en-US':'ja-JP';speechSynthesis.cancel();speechSynthesis.speak(u)}
function draw(){const c=$('curve'),ctx=c.getContext('2d'),W=c.clientWidth,H=150,d=devicePixelRatio||1;c.width=W*d;c.height=H*d;ctx.scale(d,d);ctx.clearRect(0,0,W,H);ctx.strokeStyle='#202735';for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(24,18+i*24);ctx.lineTo(W-10,18+i*24);ctx.stroke()}[['#ff7399',.45],['#ffc15f',1.1],['#5be1c3',2.8]].forEach(([col,s])=>{ctx.strokeStyle=col;ctx.lineWidth=2.2;ctx.beginPath();for(let x=0;x<W-38;x++){const t=x/(W-38)*7,r=Math.exp(-t/s),px=24+x,py=128-r*100;x?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.stroke()})}
function cal(){$('cal').innerHTML='';const now=new Date();for(let i=27;i>=0;i--){const d=new Date(now);d.setDate(now.getDate()-i);const n=st.d[dayKey(d.getTime())]||0,el=document.createElement('div');el.className='day '+(n>8?'c':n>3?'b':n?'a':'');el.textContent=d.getDate();$('cal').appendChild(el)}}
function corpusAudit(){const enWords=new Set();ITEMS.forEach(x=>(x.en.toLowerCase().match(/[a-z']+/g)||[]).forEach(w=>enWords.add(w)));const funcs=new Set(ITEMS.map(x=>x.func));return{words:enWords.size,funcs:funcs.size,scenes:SCENES.length,exp:ITEMS.length,turns:Object.values(DIALOGUES).reduce((a,b)=>a+b.length,0)}}
function renderAudit(){const a=corpusAudit();$('audit').innerHTML=`<div class=auditGrid><div class=audit><b>${a.exp}</b><span>双语高频表达</span></div><div class=audit><b>${a.turns}</b><span>真实对话回合</span></div><div class=audit><b>${a.words}</b><span>英文词形覆盖</span></div><div class=audit><b>${a.funcs}</b><span>交际功能标签</span></div></div><div class=tip style="margin-top:10px">内容审计：20 个核心场景已达到每场 20 条表达；训练目标覆盖开场、回应、追问、澄清、支付、拒绝、求助、对话修复与收尾。当前仍属于“基础日常交流”层，不等于自由流利交流；后续需要继续增加听力口音、多样说法和不可预测追问。</div>`}
const QS=[['便利店里店员问你怎么支付。你想用卡。直接回答。','Can I pay by card? / カードで払えますか？'],['对方说太快，你只想让他把最后一句再说一遍。','Could you repeat the last part? / 最後の部分をもう一度お願いします。'],['朋友邀你今晚吃饭，但你已有安排。自然拒绝并保留未来窗口。','Sorry, I already have plans. Maybe next time. / ごめん、もう予定がある。また今度ね。'],['酒店 Wi‑Fi 连不上，你需要前台处理。','The Wi-Fi isn’t working. Could someone take a look? / Wi-Fiがつながりません。誰か見に来てもらえますか？']];
function renderQ(){$('q').textContent=QS[qx][0];$('ans').value='';$('fb').classList.remove('show')}
function submitQ(){if(!$('ans').value.trim())return toast('先给出回答');$('fb').innerHTML=`参考可行回答：${QS[qx][1]}<br>检查点：是否完成现实意图，而不是逐字翻译。`;$('fb').classList.add('show');setTimeout(()=>{qx=(qx+1)%QS.length;renderQ()},3300)}
function smoke(){const errs=[];if(ITEMS.length!==400)errs.push('表达数');if(SCENES.length!==20)errs.push('场景数');if(Object.values(DIALOGUES).some(x=>x.length!==10))errs.push('对话轮数');['home','learn','library','dialog','check','vid','dvid','coverage'].forEach(id=>{if(!$(id))errs.push(id)});console[errs.length?'warn':'log']('TalkLoop v8 smoke',errs.length?errs:'passed')}
window.addEventListener('resize',()=>{if($('check').classList.contains('on'))draw()});refresh();render();renderQ();renderAudit();smoke();