const KEY='talkloop9';
let st=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||{m:{},h:[],d:{},mood:'good',lang:'en',vis:{}}}catch(e){return{m:{},h:[],d:{},mood:'good',lang:'en',vis:{}}}})();
let ix=0,lang=st.lang||'en',filter='all',dScene='greeting',dTurn=0,dLang=lang,qx=0;
const $=x=>document.getElementById(x),app=$('app');app.dataset.mood=st.mood||'good';
const EXTRA={en:{social:['https://videos.pexels.com/video-files/8522987/8522987-hd_1080_1920_30fps.mp4','https://videos.pexels.com/video-files/5971791/5971791-uhd_2160_4096_25fps.mp4','https://videos.pexels.com/video-files/6602066/6602066-hd_1080_1920_25fps.mp4'],retail:['https://videos.pexels.com/video-files/9046237/9046237-uhd_2160_3840_24fps.mp4','https://videos.pexels.com/video-files/9046233/9046233-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/8554081/8554081-hd_1080_1920_25fps.mp4'],travel:['https://videos.pexels.com/video-files/8553596/8553596-uhd_2160_3840_24fps.mp4','https://videos.pexels.com/video-files/7820465/7820465-hd_1920_1080_25fps.mp4'],health:['https://videos.pexels.com/video-files/30141938/12927309_1080_1920_30fps.mp4'],work:['https://videos.pexels.com/video-files/10373944/10373944-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/5971791/5971791-uhd_2160_4096_25fps.mp4']},jp:['https://videos.pexels.com/video-files/12893501/12893501-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/9046233/9046233-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/6540258/6540258-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/10373944/10373944-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/6602066/6602066-hd_1080_1920_25fps.mp4','https://videos.pexels.com/video-files/8554081/8554081-hd_1080_1920_25fps.mp4']};
const warmed=new Map();
function warm(src){if(!src||warmed.has(src))return;const v=document.createElement('video');v.preload='auto';v.muted=true;v.playsInline=true;v.src=src;try{v.load()}catch(e){}warmed.set(src,v);if(warmed.size>10){const k=warmed.keys().next().value;const old=warmed.get(k);try{old.pause();old.removeAttribute('src')}catch(e){}warmed.delete(k)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(st))}catch(e){}}
function dayKey(ts=Date.now()){const d=new Date(ts);return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function marked(t='all'){return ITEMS.filter(x=>st.m[x.id]&&(t==='all'||st.m[x.id].type===t))}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(window._tt);window._tt=setTimeout(()=>$('toast').classList.remove('show'),1200)}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));$(p).classList.add('on');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.p===p));if(p==='home')refresh();if(p==='library')renderLib();if(p==='dialog')renderD();if(p==='check'){draw();cal();renderAudit();renderQ()}document.querySelector('.content').scrollTop=0}
function openLib(f){filter=f;go('library')}
function row(n,a,b){const p=Math.round(a/Math.max(1,b)*100);return `<div class=row><div>${n}<div class=bar><i style="width:${p}%"></i></div></div><span class=tiny>${a}/${b} · ${p}%</span></div>`}
function refresh(){const a=marked().length,b=marked('bad').length,m=marked('mid').length,g=marked('good').length;$('nAll').textContent=a;$('nBad').textContent=b;$('nMid').textContent=m;$('nGood').textContent=g;const gr=g/Math.max(1,a);$('level').textContent=gr>.68?'L4 · 无提示能说':gr>.32?'L3 · 提示后能说':'L2 · 听得懂';const sc=new Set(marked().map(x=>x.scene.id)).size;const due=ITEMS.filter(x=>st.m[x.id]&&st.m[x.id].next<=Date.now()).length;$('coverage').innerHTML=row('核心场景',sc,20)+row('高频表达',a,400)+row('对话修复',marked().filter(x=>x.scene.id==='repair').length,20);$('dueHome').textContent=due;$('weakHome').textContent=b+m;$('recentHome').textContent=st.h.length?ITEMS.find(x=>x.id===st.h[0].id)?.en||'继续训练':'尚未开始';$('homeFocus').textContent=due?`${due} 条到期 · 优先处理`:'队列已准备';$('midRail').textContent=m?`${m} 条模糊表达待强化`:'当前暂无模糊表达';renderHomeRecent()}
function renderHomeRecent(){const recent=[];for(const h of st.h){const x=ITEMS.find(i=>i.id===h.id);if(x&&!recent.some(r=>r.id===x.id))recent.push(x);if(recent.length===5)break}if(!recent.length){recent.push(...ITEMS.slice(0,5))}$('homeRecent').innerHTML=recent.map(x=>`<button onclick="ix=${ITEMS.indexOf(x)};render();go('learn')"><div><b>${x.en}</b><span>${x.jp} · ${x.scene.zh}</span></div><em>→</em></button>`).join('')}
function interval(type,reps){if(type==='bad')return Math.max(1,3-Math.min(reps-1,2))*3600e3;if(type==='mid')return (12+Math.min(reps-1,4)*6)*3600e3;return (48+Math.min(reps-1,8)*24)*3600e3}
function grade(type){const x=ITEMS[ix],prev=st.m[x.id],reps=prev&&prev.type===type?(prev.reps||1)+1:1;st.m[x.id]={type,reps,time:Date.now(),next:Date.now()+interval(type,reps)};st.h.unshift({id:x.id,type,time:Date.now()});st.h=st.h.slice(0,800);st.d[dayKey()]=(st.d[dayKey()]||0)+1;st.mood=type;app.dataset.mood=type;save();toast(type==='bad'?'已进入不熟强化':type==='mid'?'已进入模糊强化':'已进入熟练长间隔');refresh();animateGrade(type);setTimeout(()=>{ix=pickNextIndex();render()},170)}
function animateGrade(type){const card=$('learnCard');card.style.transform=type==='good'?'translateX(22px)':type==='bad'?'translateX(-22px)':'scale(.985)';card.style.opacity='.72';setTimeout(()=>{card.style.transform='';card.style.opacity='1'},180)}
function pickNextIndex(){const now=Date.now();return ITEMS.map((x,i)=>{const m=st.m[x.id];let score=!m?24:m.next<=now?(m.type==='bad'?100:m.type==='mid'?70:35):(m.type==='bad'?42:m.type==='mid'?24:4);score+=Math.random()*8;return{i,score}}).sort((a,b)=>b.score-a.score)[0].i}
function previewNext(){ix=pickNextIndex();render();toast('已切换到下一条自适应推荐')}
function startAdaptive(){ix=pickNextIndex();render();go('learn')}
function category(item){const id=item.scene.id;if(['greeting','intro','smalltalk','appointment','friends','invite','thanks'].includes(id))return'social';if(['convenience','cafe','restaurant','shopping'].includes(id))return'retail';if(['transport','directions','hotel'].includes(id))return'travel';if(id==='health')return'health';return'work'}
function uniq(a){return [...new Set(a.filter(Boolean))]}
function pools(item,l){const base=((l==='jp'?VIDEO_JP:VIDEO_EN)[item.scene.id]||[]);return l==='jp'?uniq([...base,...EXTRA.jp]):uniq([...base,...(EXTRA.en[category(item)]||[]),...EXTRA.en.social.slice(0,1)])}
const mediaState=new WeakMap();
function stopMedia(v){const s=mediaState.get(v);if(s&&s.timer)clearTimeout(s.timer);v.onloadedmetadata=v.onerror=v.oncanplay=v.ontimeupdate=null;try{v.pause()}catch(e){}}
function prepareNext(item,l){const p=pools(item,l);if(!p.length)return;const seed=hash(item.id+'|'+l+'|next');warm(p[seed%p.length]);warm(p[(seed+1)%p.length])}
function remix(item,v,ph,l=lang,reason='auto',shadeId){stopMedia(v);const pool=pools(item,l),scene=v.closest('.scene'),shade=shadeId?$(shadeId):scene.querySelector('.mediaShade');const k=item.id+'|'+l;st.vis[k]=(st.vis[k]||0)+1;save();const visit=st.vis[k],seed=hash(k+'|'+visit),src=pool.length?pool[seed%pool.length]:'';const clipLen=5+(seed%3),start=(seed%9)+((item.pi||0)%4)*.7;ph.style.backgroundImage=`url('${item.scene.img}')`;ph.style.display='block';scene.classList.remove('video-ready');scene.classList.add('loading');if(shade)shade.style.display='grid';if(!src){scene.classList.remove('loading');return}warm(src);const fallback=()=>{scene.classList.remove('loading');scene.classList.remove('video-ready');v.style.opacity='0';ph.style.opacity='1'};v.src=src;v.preload='auto';v.muted=true;v.playsInline=true;v.onerror=fallback;v.oncanplay=()=>{const dur=isFinite(v.duration)?v.duration:0,s=Math.max(0,Math.min(start,Math.max(0,dur-clipLen-.2)));v._s=s;v._len=Math.min(7,Math.max(4,Math.min(clipLen,dur||clipLen)));try{v.currentTime=s}catch(e){}scene.classList.remove('loading');scene.classList.add('video-ready');if(shade)shade.style.display='none';v.play().catch(()=>{});prepareNext(item,l)};v.ontimeupdate=()=>{if(v.currentTime>=(v._s||0)+(v._len||clipLen)-.08){const dur=isFinite(v.duration)?v.duration:0;const nextStart=dur>10?Math.min((v._s||0)+3.1,Math.max(0,dur-(v._len||clipLen)-.2)):v._s||0;v._s=nextStart;try{v.currentTime=nextStart}catch(e){}v.play().catch(()=>{})}};v.load();mediaState.set(v,{src})}
function render(){const x=ITEMS[ix],s=x.scene;$('tag').textContent=s.tag;$('meta').innerHTML=`${s.meta}<small>${s.zh} · ${x.func} · ${x.action}</small>`;$('live').innerHTML='<i></i>LIVE';remix(x,$('vid'),$('photo'),lang,'render','mediaShade');$('intent').textContent=`${s.zh} · ${x.func}`;$('enP').textContent=x.en;$('enR').textContent='自然语速 → 慢速 → 无提示主动说';$('jpP').textContent=x.jp;$('jpR').textContent='女性交流场景视频池 · 日语口语语境';$('meaning').textContent=x.cn;$('meaning').classList.remove('show');$('tip').textContent=lang==='jp'?'优先匹配女性日常交流素材；视频首帧未准备好时先保留场景封面，避免黑屏等待。':'按场景、动作和训练次数切换素材；下一条素材会提前预热，减少等待。';$('counter').textContent=(ix+1)+'/400';$('prog').style.width=(ix+1)/400*100+'%';$('en').style.display=lang==='en'?'block':'none';$('jp').style.display=lang==='jp'?'block':'none';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.l===lang));$('nextLabel').textContent=ITEMS[pickNextIndex()]?.en||'自适应推荐';$('sameSceneLabel').textContent=`${s.zh} · 10轮对话`;prepareNext(x,lang)}
function langSet(l){lang=l;st.lang=l;save();render()}
function manualRemix(){remix(ITEMS[ix],$('vid'),$('photo'),lang,'manual','mediaShade');toast('已切换场景素材')}
function speak(rate=1){const x=ITEMS[ix];if(!('speechSynthesis'in window))return toast('浏览器不支持系统发音');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(lang==='en'?x.en:x.jp);u.lang=lang==='en'?'en-US':'ja-JP';u.rate=rate;speechSynthesis.speak(u)}
let drag={active:false,startX:0,startY:0,dx:0,ignore:false,lastTouch:0};const card=$('learnCard');
function resetDrag(){card.style.transform='';card.style.opacity='1';drag.active=false;drag.dx=0}
card.addEventListener('pointerdown',e=>{drag.ignore=!!e.target.closest('button,input,select');if(drag.ignore)return;drag.active=true;drag.startX=e.clientX;drag.startY=e.clientY;drag.dx=0;try{card.setPointerCapture(e.pointerId)}catch(_){}});
card.addEventListener('pointermove',e=>{if(!drag.active||drag.ignore)return;const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(Math.abs(dx)>Math.abs(dy)&&Math.abs(dx)>8){drag.dx=dx;card.style.transform=`translateX(${Math.max(-72,Math.min(72,dx*.34))}px) rotate(${dx*.012}deg)`;card.style.opacity=String(Math.max(.68,1-Math.abs(dx)/520))}});
card.addEventListener('pointerup',e=>{if(!drag.active||drag.ignore)return;const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;resetDrag();if(Math.abs(dx)>42&&Math.abs(dx)>Math.abs(dy)*1.12){drag.lastTouch=Date.now();grade(dx>0?'good':'bad')}});
card.addEventListener('pointercancel',resetDrag);
card.addEventListener('touchstart',e=>{if(Date.now()-drag.lastTouch<500||e.target.closest('button,input,select'))return;drag.startX=e.touches[0].clientX;drag.startY=e.touches[0].clientY},{passive:true});
card.addEventListener('touchend',e=>{if(Date.now()-drag.lastTouch<500||e.target.closest('button,input,select'))return;const dx=e.changedTouches[0].clientX-drag.startX,dy=e.changedTouches[0].clientY-drag.startY;if(Math.abs(dx)>42&&Math.abs(dx)>Math.abs(dy)*1.12)grade(dx>0?'good':'bad')},{passive:true});
function renderFilters(){const fs=[['all','全部'],['bad','不熟'],['mid','模糊'],['good','熟练']];$('filters').innerHTML=fs.map(([k,n])=>`<button class="f ${filter===k?'on':''}" onclick="filter='${k}';renderLib()">${n}</button>`).join('')}
function renderLib(){renderFilters();const arr=marked(filter).sort((a,b)=>(st.m[b.id]?.time||0)-(st.m[a.id]?.time||0));$('lib').innerHTML=arr.length?arr.map(x=>`<button class=rec onclick="ix=${ITEMS.indexOf(x)};render();go('learn')"><div class=th style="background-image:url('${x.scene.img}')"></div><div class=in><b>${x.en}</b><span>${x.jp} · ${st.m[x.id].type}</span></div></button>`).join(''):`<div class="card" style="padding:24px;grid-column:1/-1;color:#8f99ad">当前分类暂无记录。</div>`}
function fillDialogSelect(){if($('dsel').options.length)return;$('dsel').innerHTML=SCENES.map(s=>`<option value="${s.id}">${s.zh} · 10轮</option>`).join('')}
function renderD(){fillDialogSelect();const sc=SCENES.find(s=>s.id===dScene)||SCENES[0],turns=DIALOGUES[sc.id],t=turns[dTurn],fake={id:sc.id+'-d'+dTurn,scene:sc,pi:dTurn,action:t.action};$('dtag').textContent=sc.tag;$('dmeta').innerHTML=`${sc.meta}<small>${sc.zh} · 第 ${dTurn+1}/10 轮 · ${t.func}</small>`;remix(fake,$('dvid'),$('dphoto'),dLang,'dialog','dshade');$('dbub').classList.toggle('you',t.role==='u');$('drole').textContent=t.role==='u'?'You · 你':'Partner · 对方';$('dtext').textContent=dLang==='en'?t.en:t.jp;$('dcount').textContent=(dTurn+1)+'/10';$('dlang').textContent=dLang==='en'?'日本語':'English'}
function nextD(){dTurn=(dTurn+1)%10;renderD()}
function remixD(){const sc=SCENES.find(s=>s.id===dScene),t=DIALOGUES[sc.id][dTurn],fake={id:sc.id+'-d'+dTurn,scene:sc,pi:dTurn,action:t.action};remix(fake,$('dvid'),$('dphoto'),dLang,'manual','dshade')}
function speakD(){const t=DIALOGUES[dScene][dTurn];if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(dLang==='en'?t.en:t.jp);u.lang=dLang==='en'?'en-US':'ja-JP';speechSynthesis.cancel();speechSynthesis.speak(u)}
function draw(){const c=$('curve'),ctx=c.getContext('2d'),W=c.clientWidth,H=150,d=devicePixelRatio||1;c.width=W*d;c.height=H*d;ctx.scale(d,d);ctx.clearRect(0,0,W,H);ctx.strokeStyle='#202735';for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(24,18+i*24);ctx.lineTo(W-10,18+i*24);ctx.stroke()}[['#ff7399',.45],['#ffc15f',1.1],['#5be1c3',2.8]].forEach(([col,s])=>{ctx.strokeStyle=col;ctx.lineWidth=2.2;ctx.beginPath();for(let x=0;x<W-38;x++){const t=x/(W-38)*7,r=Math.exp(-t/s),px=24+x,py=128-r*100;x?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.stroke()})}
function cal(){$('cal').innerHTML='';const now=new Date();for(let i=27;i>=0;i--){const d=new Date(now);d.setDate(now.getDate()-i);const n=st.d[dayKey(d.getTime())]||0,el=document.createElement('div');el.className='day '+(n>8?'c':n>3?'b':n?'a':'');el.textContent=d.getDate();$('cal').appendChild(el)}}
function corpusAudit(){const enWords=new Set();ITEMS.forEach(x=>(x.en.toLowerCase().match(/[a-z']+/g)||[]).forEach(w=>enWords.add(w)));const funcs=new Set(ITEMS.map(x=>x.func));return{words:enWords.size,funcs:funcs.size,scenes:SCENES.length,exp:ITEMS.length,turns:Object.values(DIALOGUES).reduce((a,b)=>a+b.length,0)}}
function renderAudit(){const a=corpusAudit();$('audit').innerHTML=`<div class=auditGrid><div class=audit><b>${a.exp}</b><span>双语高频表达</span></div><div class=audit><b>${a.turns}</b><span>真实对话回合</span></div><div class=audit><b>${a.words}</b><span>英文词形覆盖</span></div><div class=audit><b>${a.funcs}</b><span>交际功能标签</span></div></div><div class=tip style="margin-top:10px">当前 20 个核心场景每场 20 条表达，覆盖开场、回应、追问、澄清、支付、拒绝、求助、修复与收尾。继续提高真实交流能力时，重点应放在口音多样性、自然变体和不可预测追问，而不是继续无边界堆词。</div>`}
const QS=[['便利店里店员问你怎么支付。你想用卡。直接回答。','Can I pay by card? / カードで払えますか？'],['对方说太快，你只想让他把最后一句再说一遍。','Could you repeat the last part? / 最後の部分をもう一度お願いします。'],['朋友邀你今晚吃饭，但你已有安排。自然拒绝并保留未来窗口。','I already have plans tonight. Maybe next time.'],['酒店前台找不到你的预订，你下一句如何继续解决？','Could you check under my name again?']];
function renderQ(){$('q').textContent=QS[qx][0];$('ans').value='';$('fb').classList.remove('show')}
function submitQ(){if(!$('ans').value.trim())return toast('先回答一句');$('fb').innerHTML=`一个可行答案：${QS[qx][1]}<br>下一题会改变条件。`;$('fb').classList.add('show');setTimeout(()=>{qx=(qx+1)%QS.length;renderQ()},2800)}
function smoke(){const issues=[];if(ITEMS.length!==400)issues.push('ITEMS!=400');if(SCENES.length!==20)issues.push('SCENES!=20');if(!DIALOGUES||Object.keys(DIALOGUES).length!==20)issues.push('dialogues');if(!$('learnCard'))issues.push('learnCard');if(issues.length)console.warn('TalkLoop v9',issues);else console.log('TalkLoop v9 smoke passed')}
refresh();render();renderQ();prepareNext(ITEMS[ix],lang);smoke();